CC=gcc
CFLAGS=-std=c99 -Wall -Wextra -g
LDFLAGS=
EXEC=test_morse

# Makefile à compléter
.PHONY: clean enonce
enonce:
	@echo "Complétez d'abord le Makefile pour compiler cet exercice."

clean:
	rm -f *~ *.o $(EXEC)

.PHONY: progress

progress:
	@../../../.progress/update $(shell basename "$(shell pwd)")
