
.PHONY: enonce
enonce:
	@echo "Commencez par compléter le Makefile de cet exercice."

.PHONY: clean
clean:
	rm -rf *.o *~ main

.PHONY: progress

progress:
	@../../../.progress/update $(shell basename "$(shell pwd)")
