# Compléter le Makefile effectuant les opérations suivantes :
# - Génération de l'exécutable : <nomexecutable>
# - <nomexecutable> : avec options de compilation standards et mode débogage pour utilisation de ddd/gdb et valgrind
# - Génération du fichier préprocesseur: <nomexecutable>_preprocesseur.txt
# - Règle clean : supprimer les fichiers .o ainsi que l'exécutable et le fichier préprocesseur générés 
CC=gcc

.PHONY: progress

progress:
	@../../../.progress/update $(shell basename "$(shell pwd)")
